python==3.8
typing==3.10.0.0
matplotlib==3.7.2
pytorch==2.2.0
torchvision==0.15.2
pandas==2.0.3
tqdm==4.65.0
yaml==6.0.1
scipy==1.10.1
scikit-learn==1.3.0
av==11.0.0
opencv==4.6.0
pre-commit==3.4.0
pyqt==5.15.10
tensorboard==2.10.0
